### ISSUE TITLE
ユーザー情報が取得できない問題

### ISSUE THREAD

**Issue by ieshige** [cohki0305/SlackCloneApp#41]
①聞きたいことの一行まとめ
ユーザー情報が取得できない
②起きている問題（起きている現象の詳細/エラーメッセージ/スクリーンショット）
ChartForm_vue.に下記コードを入れると、表示されるはずの情報がデベロッパーツールで確認できない

入れたコード
this.setUser(user)
console.log(this.$store.state.user)

スクリーンショット
![SnapCrab_slack-clone-app - Google Chrome_2020-5-6_17-23-51_No-00](https://user-images.githubusercontent.com/29097968/81154862-4bb68600-8fbf-11ea-9ee1-a8cf15cff64f.jpg)

③ソースコード（関連するソースコード/全ソースコード）
該当コード
https://gist.github.com/ieshige/dced14f3c8ee155c3edd5fbe21a36254

全ソースコード
https://github.com/ieshige/SlackCloneApp2

④問題解決するために試したこと（コードもあれば追記）
サーバーの再起動Ctrl+C

デベロッパーツールのコンソールでdisplayNameと入れると
VM28035:1 Uncaught ReferenceError: displayName is not defined
    at <anonymous>:1:1
というエラーがでる
emailやphotoURLなども同じエラーがでる

Message.vueのコメントアウトしてあるdisplayNameを戻したが別のエラーが出たのでもどした
出たエラー
TypeError: Cannot read property 'name' of undefined
    at VueComponent.displayName

firebaseの方からデータが引っ張ってこれていないのかと思って別のアカウントでfirebaseを作り直してそちらを設定してみたが症状は同じだった。

⑤問題について自分なりに考えたこと（デバッグ結果/検索結果/自分なりの原因予想）
user情報が取得できていない
投稿した内意用はfirebaseに登録されているので連携エラーではない
コードを一行一行コピペしてタイポがないか確認

store/index.jsにて
export const mutations = {
  setUser(state, payload) {
    state.user = payload
  },
}
のpayloadをuserに戻してみたりしたが意味なし

⑥当該コンテンツを購入したnoteのアカウント
ieshige
⑦noteのどのあたりまでやったのか

5-4. ユーザ情報を投稿に入れるまで無理やり進めました

ちなみに投稿にユーザー情報をいれるのところで下記コードを入れるとfirebaseエラーが出ます
投稿にアバターも表示されず、おそらく質問の内容の問題と同じことが原因かと思います
+       user: {
+         name: this.user.displayName,
+         thumbnail: this.user.photoURL
+       }

エラーメッセージ
client.js?06a0:77 FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: undefined (found in field user.name)

**Comment by cohki0305** [comment]
[ここ](https://gist.github.com/ieshige/dced14f3c8ee155c3edd5fbe21a36254#file-chatform-vue-L75)の上に debugger をいれてみて、まずはログインできているか確認したほうが良いかなと思いました！

ソースコードのインデントがかなりめちゃくちゃでかなり見通し悪いので、まずは整え他方が良いかと思いました。見た目が悪いとデバッグはかなり難しくなったりします。

**Comment by ieshige** [comment]
お返事ありがとうございます！

ご指摘通りログインできていませんでした。
debuggerを入れるまでログイン画面が出てこなかったので気が付きませんでした。

ログイン後ユーザー情報の取得もできていました。

ご指摘のインデントもほかの方のコードを参考にして奇麗にしていきたいと思います。

お忙しい中ありがとうございました。
