### ISSUE TITLE
npm run devした後ローカルホストで最初の画面が立ち上がりません

### ISSUE THREAD

**Issue by akusano72** [cohki0305/SlackCloneApp#9]
タイトルのとおりです。
npm installした後、npm run devで

 READY  Server listening on http://localhost:3000 

までは行きましたが、ブラウザでhttp://localhost:3000 にアクセスしても
Cannot GET / と表示されるだけで最初の画面が立ち上がりません。

noteの説明どおりに操作しているつもりなのですが
何が悪いのか見当もつかないので質問させていただきました。。
何か心当たりがありましたらご教授いただけますと助かります。

**Comment by akusano72** [comment]
すみません、、、裏で起動してたvscodeのターミナルが同じlocalhost:3000でローカルサーバー立ち上げてたのが原因でした…。お騒がせいたしましたm(_ _)m

**Comment by cohki0305** [comment]
解決してよかったです！
